version: '3'

services:
  angular:
    image: teracy/angular-cli
    command: ng build
    volumes:
    - .:/usr/src/app
    working_dir: /usr/src/app
  nginx:
    image: nginx
    volumes:
    - ./dist/IMAGE-frontend:/usr/share/nginx/html:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "4200:80"
